# Generated by Django 2.0.7 on 2018-07-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_control', '0002_auto_20180722_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='mode',
            field=models.IntegerField(default=0, verbose_name='Switch Mode'),
        ),
    ]
