# Generated by Django 2.0.7 on 2018-07-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_control', '0003_switch_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='mode',
        ),
        migrations.AlterField(
            model_name='switch',
            name='type',
            field=models.CharField(choices=[('T', 'On'), ('D', 'Off')], max_length=1),
        ),
    ]
